using Plots, StatsPlots, Measures


function plotHist(historyData)
    N = length(historyData)
    x = 1:N

    p = plot(x, historyData, label= "observations") 
    plot!(p, legend=:outerbottom, legendcolumns=3)
    title!(p, "Historical Data")
    xlabel!(p,"time")
    ylabel!(p, "MWh")

    return p
end

function plotForecast(historyData, forecastData)
    T = length(historyData)
    window = T-100:T
    T_hat = length(forecastData)
    historical_dates = 1:T
    forecast_dates = T+1 : (T + T_hat)

    p = plot(
        historical_dates[window], historyData[window],
        label="Historical Load",
        color=:blue,
        lw=2,
        xlabel="Date",
        ylabel="Load (MW)",
        legend=:topright,
        title="Load Forecast with Historical Data"
    )
    plot!(p, 
        forecast_dates, forecastData,
        label="Forecast Load",
        color=:red,
        lw=2,
        linestyle=:dash
    )

    # # Highlight forecast region
    # highlight_area_start = last(historical_dates)
    # highlight_area_end = last(forecast_dates)
    # plot!(
    #     [highlight_area_start, highlight_area_end],
    #     [minimum(loads), minimum(loads)],
    #     color=:gray,
    #     alpha=0.2,
    #     lw=0,
    #     fill_between=(highlight_area_start, highlight_area_end),
    #     label=""
    # )
    

    return p
end

function plotForecastSlidingWindow(hmm::HMM, observations, forecastHorizon::Int, firstIndexToPlot::Int)
    # Set Parameters
    T = length(observations)
    indeces = firstIndexToPlot:T
    observationsAsIndeces = translateObservationsAsIntToIndex(observations, hmm.observationSpace)

    # Create Base Plot
    p = plot(
        indeces, observations[indeces],
        color=:black,
        lw=2,
        xlabel="Index",
        ylabel="Observation",
        title="Sliding Window Forecast (Best Path)"
    )

    # Add Forecastlines
    for i in indeces 
        indexForecast = i:(i + forecastHorizon)
        forecastAsIndeces, likelihood_forecast = bestPathPrognosis(hmm, observationsAsIndeces[1:i], forecastHorizon)
        forecast = translateIndexToObservations(forecastAsIndeces, hmm.observationSpace)

        startPointWithForecast = [observations[i]; forecast]
        
        colors = [RGBA(0, 0.0, 1, alpha) for alpha in LinRange(0.5, 0.2, (forecastHorizon+1))]

        plot!(p, 
            indexForecast, startPointWithForecast,
            color=colors,
            lw=2,
        )
    end

    return p
end

function plotDistributionForecastWithViolin(hmm::HMM, observationHist, observationFuture, distributionForecast::Vector{Vector{Float64}}, header = "")
    T = length(observationHist)
    H = length(observationFuture)

    # Plot historical data
    p = plot(collect(1:T), observationHist, title = header, label= "historical observations", legend=false) 

    # Plot distribution via violin plots
    for i in 1:H
        frequency_i = transformDistributionVectorToFrequencyVector(hmm.observationSpace, distributionForecast[i])
        violin!(p, [i+T], frequency_i, color=:lightcyan2)
    end
    if H < 25 
        plot!(p, T:T+H, vcat([observationHist[end]], observationFuture), color = :red )
    else
        plot!(p, T:T+H, vcat([observationHist[end]], observationFuture), color = :black )
    end
    return p
end



function plotPITHistogram((observationSpace, infoBins), observations, distributionForecastVector::Vector{Vector{Float64}}, header = "")
    N = length(distributionForecastVector)
    pits = zeros(Float64, N)
    rightNodes = [ infoBin[1] + infoBin[2] for infoBin in infoBins]

    for t in 1:N
        distributionCDF = cumsum(distributionForecastVector[t])
        distributionCDF[end] = 1.
        pits[t] = pitValue((observationSpace, infoBins, rightNodes), (distributionForecastVector[t], distributionCDF), observations[t])
        
        if pits[t] > 1
            println("ACHTUNG: $(pit[t]) at time instant $N. Data: obs: $(observations[t])  \n)")
        end
    end

    edges = 0:0.1:1
    h = fit(Histogram, pits, edges)
    max_height = maximum(h.weights)

    # Plot
    histogram(
        pits,
        bins = 0:0.1:1,
        normalize = :probability,
        color = :lightblue,
        edgecolor = :black,
        legend = false,
        xlabel = "PIT",
        ylabel = "Relative Frequency",
        title = header,
        framestyle = :box,
        grid = true,
        xticks = 0:0.1:1,
        yticks = 0:0.02:0.16,
        # left_margin = 10pt,
        # size = (800, 500),
        xlim = (0, 1),
        ylim = (0, 0.16),  # 10% above tallest bar
        dpi = 300
    )

    # Expected uniform line
    hline!(
        [0.1],
        color = :red,
        linestyle = :dash,
        linewidth = 2,
        label = "Expected probability"
)
end

# Generates an artificial PIT Histogram
# pit sample generated by predefined probabilities 'probs'
function artificialPITHistogram(fileName::String)
    values = 0.05:0.1:0.95
    probs = [15, 13, 10, 7, 5, 5, 7, 10, 13, 15]
    # underdis: [5, 7, 10, 13, 15, 15, 13, 10, 7, 5]
    # overdis: [15, 13, 10, 7, 5, 5, 7, 10, 13, 15]
    # skewed: [5, 6, 7, 8, 9, 11, 12, 13, 14, 15] ./ 100
    pits = sample(values, Weights(probs), 2000)

    # Plot
    plt = histogram(
        pits,
        bins = 0:0.1:1,
        normalize = :probability,
        color = :lightblue,
        edgecolor = :black,
        legend = false,
        xlabel = "PIT",
        ylabel = "Relative Frequency",
        framestyle = :box,
        grid = true,
        xticks = 0:0.1:1,
        yticks = 0:0.02:0.16,
        # left_margin = 10pt,
        # size = (800, 500),
        xlim = (0, 1),
        ylim = (0, 0.16),  # 10% above tallest bar
        dpi = 300
    )

    # Expected uniform line
    hline!(
        [0.1],
        color = :red,
        linestyle = :dash,
        linewidth = 2,
        label = "Expected probability"
    )

    # Save PIT histogram
    folderPath = "Thesis Script/plots/pit_histograms/"
    savefig(plt, folderPath*fileName)

    return plt
end

function plotHyperparameterAnalysisCRPS(hh, tableResultsVector, hyperparameterVector::Vector{Int}, numberOfStatesVector::Vector{Int}, hyperparameterName::String)
    
    maxValue = maximum(maximum.(tableResultsVector))
    minValue = minimum(minimum.(tableResultsVector))
    lowerBoundYAxis = minValue - (maxValue - minValue) * 0.1
    upperBoundYAxis = maxValue + (maxValue - minValue) * 0.12
    
    # Plot erstellen
    subplt = Vector{Plots.Plot}(undef, 2) 
    for i in 1:2
        subplt[i] = plot(dpi = 300)
        for (j, hyperparameter) in enumerate(hyperparameterVector)
            mae_values = tableResultsVector[i][j , :]
            plot!(subplt[i],
                numberOfStatesVector, mae_values;
                lw = 4,
                marker = :circle,
                markersize = 4,
                legend=:false,
                ylim = (lowerBoundYAxis, upperBoundYAxis),
                top_margin = -7mm,
                right_margin = [1mm, 5mm][i],
                guidefontsize = 10,
                xtickfontsize = 6,
                ytickfontsize = 6,
                title = ["Equal-mass Bins", "Equidistant Bins"][i],
                #titleloc = :right, 
                titlefont = font(11),
                framestyle = :box,
            )
        end
        xlabel!("Number of States")
        ylabel!("CRPS")
    end
    legendPlt = plot(hyperparameterVector', 
                    label = ["$hyperparameter observations" for hyperparameter in hyperparameterVector] |> permutedims, 
                    legend =:top, 
                    framestyle = :none, 
                    marker = :circle,
                    legendfontsize = 7,
                    legend_column = length(hyperparameterVector),
                    bottom_margin = -1mm,
                    dpi = 300)
    plt = plot(legendPlt, subplt[1], subplt[2], 
            suptitle = "Discretization Type Analysis for Household $hh",
            layout = @layout([a{0.05h} ; [b c] ]), dpi = 300
            ) 
    return plt
end

function plotHyperparameterAnalysisLoglike(title::String, tableResults, hyperparameterVector::Vector{Int}, numberOfStatesVector::Vector{Int}, hyperparameterName::String)
        # Plot erstellen
    plt = plot(dpi = 300)
    for (i, hyperparameter) in enumerate(hyperparameterVector)
        maxLoglike = tableResults[i , :] |> filter(isfinite) |> maximum
        loglike_values = tableResults[i , :] / maxLoglike
        plot!(plt,
            numberOfStatesVector, loglike_values;
            label = "# Observations = $hyperparameter",
            lw = 4,
            marker = :circle,
            markersize = 4,
            legend=:outertopright,
        )
    end

    xlabel!("Number of States")
    ylabel!("Normed Loglikelihood")
    title!(title)
    return plt
end




